# Generated by Django 3.0.2 on 2020-01-24 07:00

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200124_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default='profilepic/default.jpg', upload_to='profilepic/'),
        ),
    ]
