# Generated by Django 3.0.2 on 2020-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/image/')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('shortname', models.CharField(max_length=20)),
                ('template', models.FileField(upload_to='blog/template/')),
            ],
        ),
    ]
