# Generated by Django 3.0.2 on 2020-01-27 20:45

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='image_field',
            field=cropperjs.models.CropperImageField(default='profilepic/default.jpg', upload_to='profilepic/'),
        ),
    ]
