# Generated by Django 3.0.2 on 2020-01-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_profilepicture_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='image_field',
        ),
    ]
