# Generated by Django 3.0.2 on 2020-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_profilepicture_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='img',
            field=models.ImageField(default='profilepic/default.jpg', upload_to=''),
        ),
    ]
