# Generated by Django 3.0.2 on 2020-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20200128_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='img',
            field=models.ImageField(default='profilepic/default.jpg', upload_to='profilepic/'),
        ),
    ]
